/**
 * Shared all-contributors emoji key mapping.
 * https://allcontributors.org/docs/en/emoji-key
 *
 * Only a subset of the full spec is used by this repo's `.all-contributorsrc`,
 * but the full key is kept here so new contribution types render sensibly
 * without code changes.
 */
export const CONTRIBUTION_EMOJI: Record<string, string> = {
  code: "💻",
  test: "⚠️",
  doc: "📖",
  example: "💡",
  ideas: "🤔",
  review: "👀",
  bug: "🐛",
  maintenance: "🚧",
  infra: "🚇",
  tool: "🔧",
  design: "🎨",
  question: "💬",
  talk: "📢",
  translation: "🌍",
  security: "🛡️",
  video: "📹",
  blog: "📝",
  audio: "🔊",
  business: "💼",
  content: "🖋",
  data: "🔣",
  eventOrganizing: "📋",
  financial: "💵",
  fundingFinding: "🔍",
  mentoring: "🧑‍🏫",
  platform: "📦",
  plugin: "🔌",
  projectManagement: "📆",
  research: "🔬",
  userTesting: "📓",
};

export const CONTRIBUTION_LABEL: Record<string, string> = {
  code: "Code",
  test: "Tests",
  doc: "Documentation",
  example: "Examples",
  ideas: "Ideas & planning",
  review: "Reviewed pull requests",
  bug: "Bug reports",
  maintenance: "Maintenance",
  infra: "Infrastructure",
  tool: "Tools",
  design: "Design",
  question: "Answering questions",
  talk: "Talks",
  translation: "Translation",
  security: "Security",
  video: "Videos",
  blog: "Blogposts",
  audio: "Audio",
  business: "Business development",
  content: "Content",
  data: "Data",
  eventOrganizing: "Event organizing",
  financial: "Financial support",
  fundingFinding: "Funding/grant finders",
  mentoring: "Mentoring",
  platform: "Platform",
  plugin: "Plugin/utility libraries",
  projectManagement: "Project management",
  research: "Research",
  userTesting: "User testing",
};
