//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.CosmosRepository.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.CosmosRepository.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A configuration is required..
        /// </summary>
        internal static string AConfigurationIsRequired {
            get {
                return ResourceManager.GetString("AConfigurationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A path is required..
        /// </summary>
        internal static string APathIsRequired {
            get {
                return ResourceManager.GetString("APathIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service collection is required..
        /// </summary>
        internal static string AServiceCollectionIsRequired {
            get {
                return ResourceManager.GetString("AServiceCollectionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service provider instance is required..
        /// </summary>
        internal static string AServiceProviderInstanceIsRequired {
            get {
                return ResourceManager.GetString("AServiceProviderInstanceIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmos Client options are required..
        /// </summary>
        internal static string CosmosClientOptionsAreRequired {
            get {
                return ResourceManager.GetString("CosmosClientOptionsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmos client provider is required..
        /// </summary>
        internal static string CosmosClientProviderIsRequired {
            get {
                return ResourceManager.GetString("CosmosClientProviderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosmos partition key name provider is required..
        /// </summary>
        internal static string CosmosPartitionKeyNameProviderIsRequired {
            get {
                return ResourceManager.GetString("CosmosPartitionKeyNameProviderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created: {0}.
        /// </summary>
        internal static string CreatedBlank {
            get {
                return ResourceManager.GetString("CreatedBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted: {0}.
        /// </summary>
        internal static string DeletedBlank {
            get {
                return ResourceManager.GetString("DeletedBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read: {0}.
        /// </summary>
        internal static string ReadBlank {
            get {
                return ResourceManager.GetString("ReadBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository options are required..
        /// </summary>
        internal static string RepositoryOptionsAreRequired {
            get {
                return ResourceManager.GetString("RepositoryOptionsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required..
        /// </summary>
        internal static string TheBlankIsRequired {
            get {
                return ResourceManager.GetString("TheBlankIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required when container per item type is false..
        /// </summary>
        internal static string TheBlankIsRequiredWhenContainerPerItemTypeIsFalse {
            get {
                return ResourceManager.GetString("TheBlankIsRequiredWhenContainerPerItemTypeIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated: {0}.
        /// </summary>
        internal static string UpdatedBlank {
            get {
                return ResourceManager.GetString("UpdatedBlank", resourceCulture);
            }
        }
    }
}
