name: pull request

on:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

jobs:
  build:
    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          3.1.402
          6.0.x

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build --no-restore
        
    - name: Set User Secrets
      working-directory: ./tests/Microsoft.Azure.CosmosRepositoryAcceptanceTests/
      run: |
        dotnet user-secrets init
        dotnet user-secrets set RepositoryOptions:ComsosConnectionString ${{ secrets.COSMOS_INTEGRATION_TEST_CONNECTION_STRING }}

    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal